### ISSUE TITLE
Python 3.7 compatibility: Fix stdlib-list upstream, vendor it or ship our own?

### ISSUE THREAD

**Issue by ericdill** [ericdill/depfinder#20]
Which is bad because we make use of this project in depfinder to figure out which modules are builtins and which are external dependencies. We can't support depfinder in py37 until stdlib-list is updated to have py37 support.

All open issues and PRs have not received a response in about 9 months. Whenever anyone cares enough about py37 and depfinder we may need to push on stdlib-list to get it moving. The [py37 support PR](https://github.com/jackmaney/python-stdlib-list/pull/9) has not received any comments from the maintainer. Or figure out alternatives. It really wouldn't be too hard to vendor in [all these modules hard-coded in the stdlib-list code base](https://github.com/jackmaney/python-stdlib-list/tree/master/stdlib_list/lists).

**Comment by tonyfast** [comment]
Is it time to push?  Python 3.7 is showing up in all the cool kids codes.

**Comment by ocefpaf** [comment]
There is a PR to add py37 support in https://github.com/jackmaney/python-stdlib-list/pull/9 but I guess someone would need to help/take over the `stdlib-list` project. If not, maybe we could "verdorize" it here?

**Comment by ericdill** [comment]
@ocefpaf @tonyfast I've got no burning need to get py3.7 support running here. It's a nice-to-have for now as far as I'm concerned. That being said, if either of you want to push on vendoring stdlib-list in this code base then go right ahead. I'm happy to review. I do like @tonyfast's suggestion of just scraping that py-modindex for 2.7, 3.5, 3.6 and 3.7 and then just vendoring those lists. 

Ideally, we'll hear back on  jackmaney/python-stdlib-list#9  and then just get commit rights to that and fix it there. If not then I'll probably push on vendoring stdlib-list here (or the equivalent suggestion from @tonyfast).

Sound good?

**Comment by ericdill** [comment]
Via email, @ocefpaf suggested that he would try and fix the python 3.7 problem in depfinder, so I'll happily check out the final code product :)

**Comment by ocefpaf** [comment]
> @ocefpaf @tonyfast I've got no burning need to get py3.7 support running here. It's a nice-to-have for now as far as I'm concerned.

I do :smile: but don't worry, I'm working on it.

> That being said, if either of you want to push on vendoring stdlib-list in this code base then go right ahead.

I'll wait a little bit for an answer in https://github.com/jackmaney/python-stdlib-list/issues/11

> I'm going to give the scraper a go at the same time; if that isn't stepping on toes?

Not at all! Please do. Note that `python-stdlib-list` itself does something similar to create the list text files, but they use sphinx directly and not the generated HTML.

**Comment by jackmaney** [comment]
I just wanted to pop in and apologize for dropping the ball on `python-stdlib-list`. Between work, illness, my wife having a heart attack, and other various emergencies, I haven't had the time to touch any of my side projects. I've sent collaborator invites for `python-stdlib-list` to three people, including @ocefpaf .

**Comment by ericdill** [comment]
> Between work, illness, my wife having a heart attack, and other various emergencies, I haven't had the time to touch any of my side projects

I'd just like to echo what @ocefpaf said. Health and family always come first. I hope that everything is going ok with you and your family now. I'd also like to personally apologize if I/we contributed any stress to your life! 

Thanks for creating stdlib-list in the first place and thanks for letting us shoulder some of the maintenance of your project.
