### ISSUE TITLE
depfinder chokes from notebooks that have non-python code

### ISSUE THREAD

**Issue by ocefpaf** [ericdill/depfinder#27]
When the notebooks has a `!` to call a system CLI depfinder fails ungracefully. See

https://gist.github.com/rsignell-usgs/c5b5e5941cc766d3f77868b8aa533e99

Ping @rsignell-usgs

**Comment by ericdill** [comment]
I thought @tonyfast took care of this issue

**Comment by ericdill** [comment]
Isn't this fixed by #18?

**Comment by ocefpaf** [comment]
BTW, just adding `~/Dropbox/pymodules/01-forks/nbrr/tests` to one of my tests did not trigger the error. It may be an old version. Closing this for now until we have more info. Sorry to bug you @ericdill!
