### ISSUE TITLE
Handle if/else/elif blocks for imports

### ISSUE THREAD

**Issue by CJ-Wright** [ericdill/depfinder#45]
Imports inside if statements most likely are questionable so we might treat them as such.

**Comment by ericdill** [comment]
Agreed. There's an ast.If node. I wonder if there are any others we need to consider? ast.for?

**Comment by CJ-Wright** [comment]
`if` sounds good, `for` sounds a bit odd

**Comment by ericdill** [comment]
Yeah mostly just trying to figure out all of the weird places people would import

**Comment by CJ-Wright** [comment]
We could also just track what was the parent node in the tree. We are currently reading all of the python packages on conda-forge, which is a pretty good fuzzing system.
