### ISSUE TITLE
%%time magic skips cell?

### ISSUE THREAD

**Issue by rsignell-usgs** [ericdill/depfinder#67]
It looks like magics should be covered in https://github.com/ericdill/depfinder/pull/18 but when I tried running this notebook: 
https://github.com/rsignell-usgs/esip-qhub-notebooks/blob/main/hytest/conus404_consolidated_zarr.ipynb
the result was:
```
depfinder conus404_consolidated_zarr.ipynb 
{'required': ['dask']}
```
(it skipped the main import cell because of  the `%%time` magic)

When I took out the `%%time` cell magic, depfinder worked fine.

**Comment by ericdill** [comment]
Hi @rsignell-usgs -- sorry for never responding to this issue. With the current version of depfinder this issue with the `%%time` magic no longer happens. I checked the behavior on python 3.9.15, 3.10.8 and 3.11.0. 

If this is still an issue for you, help me understand the environment you're running in where this happens. I promise I'll be more attentive now that I'm actually paying attention. Sorry again for the long delay
