### ISSUE TITLE
Small web page issues

### ISSUE THREAD

**Issue by rsignell-usgs** [ericdill/depfinder#71]
* not secure, perhaps need to renew cert?   
* banner not getting formatted
![2022-06-02_15-35-47](https://user-images.githubusercontent.com/1872600/171724259-476d5114-f74e-423b-a61f-c4dca048e6d6.png)

**Comment by ocefpaf** [comment]
> * not secure, perhaps need to renew cert?
> * banner not getting formatted

None of the above. That is HTML in a rst file. It should not work :-)
