### ISSUE TITLE
Use `sys.stdlib_module_names` on Python 3.10 and newer

### ISSUE THREAD

**Issue by timj** [ericdill/depfinder#95]
`stdlib_list` only works for python versions <= 3.9. This makes `depfinder` unusable on newer Python versions. Please consider switching to `sys.stdlib_module_names` for newer pythons since this includes a full list of standard library packages.

**Comment by ocefpaf** [comment]
It does already. What version are you using?

**Comment by timj** [comment]
I filed https://github.com/conda-forge/depfinder-feedstock/issues/40
